### PR TITLE
Update zhTW.lua

### PR DESCRIPTION
**Pull request by BlueNightSky**

### CODE REVIEW

**Comment by nanjuekaien1** [comment]
@BlueNightSky 
250行增加
L.CustomSortInfoWarn = "|cFF99CC33NOTE: Use numbers only! Examples: (-1,0,3,4,37,99,-45)|r"
尾行增加
L.BagSyncInfoWindow = [[
BagSync by default only shows tooltip data from characters on connected realms. ( |cffff7d0a[CR]|r )

Connected Realms ( |cffff7d0a[CR]|r ) are servers that have been linked together.

For a complete list, please visit:
(|cFF99CC33 https://tinyurl.com/msncc7j6 |r)


|cFFfd5c63BagSync will NOT show data from your entire Battle.Net account by default. You will need to enable this!|r
( |cff3587ff[BNet]|r )

|cFF52D386If you would like to see all your characters across your entire Battle.net account ( |cff3587ff[BNet]|r ), you need to enable the option in the BagSync config window under [Account Wide].|r

The option is labeled as:
]]

**Comment by Xruptor** [comment]
@BlueNightSky  can you please add the translation for  `L.BagSyncInfoWindow `.  I'd like to have that before I push any translation since it's an important window.

**Comment by Xruptor** [comment]
It's been 3 weeks?  Not sure if you are getting any emails or updates when someone responds to a ticket on GitHub.  Can you please translate L.BagSyncInfoWindow as well @BlueNightSky ?  It would be deeply appreciated!

**Comment by nanjuekaien1** [comment]
@Xruptor  He's out of the country on business.

**Comment by Xruptor** [comment]
> @Xruptor He's out of the country on business.

Ah! That makes sense.  Thank you very much for clarifying that.  😃

**Pull request merged**
