### PR TITLE
Update koKR.lua

### PR DESCRIPTION
**Pull request by WetU**

### CODE REVIEW

**Comment by Xruptor** [comment]
WetU since I recently just put a new feature.  Normally you go ahead and do a translation right after I push.  SO before I push the next update (I hope for a long time because I'm getting tired of these small patches).  Can you please translate the following to koKR.

`L.DisplayRealmIDTags = "Display |cffff7d0a[XR]|r and |cff3587ff[BNet]|r realm identifiers."`

**Comment by WetU** [comment]
L.DisplayRealmIDTags = "서버 식별자 |cffff7d0a[XR]|r 과 |cff3587ff[BNet]|r 표시."

appropriate phrase, here.

**Comment by Xruptor** [comment]
Thanks!  Good thing I asked before pushing it in next release. :)

**Comment by Xruptor** [comment]
Last two WetU I promise!

L.DisplayRealmAstrick = "Display [*] instead of server names for |cffff7d0a[XR]|r and |cff3587ff[BNet]|r."
L.DisplayShortRealmName = "Display short realm names for |cffff7d0a[XR]|r and |cff3587ff[BNet]|r."

**Comment by WetU** [comment]
L.DisplayRealmIDTags = "서버 식별자 |cffff7d0a[타섭]|r과 |cff3587ff[BNet]|r을 표시합니다."

L.DisplayRealmAstrick = "|cffff7d0a[타섭]|r과 |cff3587ff[BNet]|r 서버 이름 대신 [*]을 표시합니다."

L.DisplayShortRealmName = "|cffff7d0a[타섭]|r과 |cff3587ff[BNet]|r 서버 이름을 축약해서 표시합니다."

I edited phrase that previous request.
also, 2 new phrases are here.

**Comment by Xruptor** [comment]
Thanks again WetU you rock!

**Pull request merged**
