### PR TITLE
fixes for dragonflight and french translation

### PR DESCRIPTION
**Pull request by neun0eil**
- Fixes for Dragonflight
- French translation (almost done)
- Bump libraries
- Remove VoidBank (as it seems to not be in the API anymore)

### CODE REVIEW

**Comment by neun0eil** [comment]
You're right, they change void storage events:
9.2.5 - https://www.townlong-yak.com/framexml/44232/Blizzard_APIDocumentation/VoidStorageInfoDocumentation.lua
10.0.0 - https://www.townlong-yak.com/framexml/live/Blizzard_APIDocumentationGenerated/VoidStorageInfoDocumentation.lua

**Comment by Xruptor** [comment]
Okay so void storage is still in the game.  They just changed how the Windows are fired onShow/Hide.

https://wowpedia.fandom.com/wiki/PLAYER_INTERACTION_MANAGER_FRAME_SHOW

Void would be 26

use /etrace to determine frame numbers

**Comment by Xruptor** [comment]
> You're right, they change void storage events: 9.2.5 - https://www.townlong-yak.com/framexml/44232/Blizzard_APIDocumentation/VoidStorageInfoDocumentation.lua 10.0.0 - https://www.townlong-yak.com/framexml/live/Blizzard_APIDocumentationGenerated/VoidStorageInfoDocumentation.lua

Okay so here is what I will do.  I will take the changes you made and apply everything except the void changes.  I'll adapt the frame show/hide changes to the new numbering sequence.

I'll give you full credit for the changes everywhere though :)

**Comment by Xruptor** [comment]
I haven't released it yet but I pushed some beta changes until I can make sure everything works.  There is also an issue with the Tooltip wireframe I need to review.

**Comment by Xruptor** [comment]
For the SetRecipeReagentItem change.  It looks like they completely changed on how Tooltips are scanned and parsed.  A lot of the callbacks have been removed and changed to a new system.

https://wowpedia.fandom.com/wiki/Patch_10.0.2/API_changes#Tooltip_Changes

**Pull request closed without merging**
