### PR TITLE
Update zhCN.lua

### PR DESCRIPTION
**Pull request by nanjuekaien1**

### CODE REVIEW

**Comment by Xruptor** [comment]
You should translate some of the examples to zhCN

(class:shaman) can be (class:<name of shaman in zhCN)

You can also do a few other examples if you like in zhCN to assist others.

**Comment by nanjuekaien1** [comment]
I'm under modification

**Comment by nanjuekaien1** [comment]
Enter LVL:> = 20 in the Advanced Search window. The following errors appear.
Interface/AddOns/BagSync/modules/search.lua:720: bad argument #1 to 'pairs' (table expected, got nil)
Count: 19

Call Stack:
[string "=(tail call)"]: ?
[string "=[C]"]: in function `pairs'
[string "@Interface/AddOns/BagSync/modules/search.lua"]:720: in function `DoSearch'
[string "@Interface/AddOns/BagSync/modules/search.lua"]:647: in function `DoAdvancedSearch'
[string "@Interface/AddOns/BagSync/modules/search.lua"]:249: in function <Interface/AddOns/BagSync/modules/search.lua:247>
[string "=[C]"]: ?
[string "@Interface/AddOns/BagSync/libs/AceGUI-3.0/AceGUI-3.0.lua"]:66: in function <...erface/AddOns/BagSync/libs/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@Interface/AddOns/BagSync/libs/AceGUI-3.0/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@Interface/AddOns/BagSync/libs/AceGUI-3.0/widgets/AceGUIWidget-EditBox.lua"]:70: in function <...ync/libs/AceGUI-3.0/widgets/AceGUIWidget-EditBox.lua:67>

**Comment by Xruptor** [comment]
it should be **lvl:>=20** not **LVL:> = 20** without uppercases and spaces.  But I will look into this thanks for catching it.

**Comment by Xruptor** [comment]
I found the issue with the code.  I'm working on the updates :)

**Comment by nanjuekaien1** [comment]
I took a few days off and my father was hospitalized.

**Comment by Xruptor** [comment]
> I took a few days off and my father was hospitalized.

OH NO! I hope he recovers and gets better soon! Take all the time you need.

**Pull request closed without merging**
