### PR TITLE
Update zhCN.lua

### PR DESCRIPTION
**Pull request by nanjuekaien1**

### CODE REVIEW

**Comment by nanjuekaien1** [comment]
`		guildtabs = {
			order = 12,
		},
		warbandtabs = {
			order = 13,
		},		
		expansion = {
			order = 10,
		},
		itemtypes = {
			order = 11,
`
Sorting can be changed to match the localised sorting.
Personal Thoughts.

**Comment by Xruptor** [comment]
> itemtypes

To do what you are suggesting would mean I have to put those under the whitelist and move the equippedbags up one to match the numbering you used.

```
		groupextra = {
			order = 2,
			type = "group",
			name = L.DisplayTooltipExtra,
			guiInline = true,
			args = {
				separator = {
					order = 0,
					type = "toggle",
					name = L.DisplayLineSeparator,
					width = "full",
					descStyle = "hide",
					get = get,
					set = set,
					arg = "display.enableTooltipSeparator",
				},
				itemid = {
					order = 1,
					type = "toggle",
					name = L.DisplayItemID,
					width = "full",
					descStyle = "hide",
					get = get,
					set = set,
					arg = "display.enableTooltipItemID",
				},
				total = {
					order = 2,
					type = "toggle",
					name = L.DisplayTotal,
					width = "full",
					descStyle = "hide",
					get = get,
					set = set,
					arg = "display.showTotal",
				},
				guildgoldtooltip = {
					order = 3,
					type = "toggle",
					name = L.DisplayGuildGoldInGoldWindow,
					width = "full",
					descStyle = "hide",
					get = get,
					set = set,
					arg = "display.showGuildInGoldTooltip",
					disabled = function() return not BSYC.tracking.guild end,
				},
				gscdisplay = {
					order = 4,
					type = "toggle",
					name = L.Display_GSC,
					width = "full",
					descStyle = "hide",
					get = get,
					set = set,
					arg = "display.enable_GSC_Display",
				},
				faction = {
					order = 5,
					type = "toggle",
					name = L.DisplayFaction..factionSmall,
					width = "full",
					descStyle = "hide",
					get = get,
					set = set,
					arg = "display.enableFaction",
				},
				guildcurrentcharacter = {
					order = 6,
					type = "toggle",
					name = L.DisplayGuildCurrentCharacter,
					width = "full",
					descStyle = "hide",
					get = get,
					set = set,
					arg = "display.showGuildCurrentCharacter",
					disabled = function() return not BSYC.tracking.guild end,
					hidden = function() return not CanGuildBankRepair end,
				},
				whitelistonly = {
					order = 7,
					type = "toggle",
					name = L.DisplayWhiteListOnly,
					width = "full",
					descStyle = "hide",
					get = get,
					set = set,
					arg = "display.enableWhitelist",
				},
				whitelistbutton = {
					order = 8,
					type = "execute",
					name = L.Whitelist,
					func = function()
						BSYC:GetModule("Whitelist").frame:Show()
					end,
					disabled = function() return not BSYC.options.enableWhitelist end,
				},
				equipbagslots = {
					order = 9,
					type = "toggle",
					name = L.DisplayEquipBagSlots,
					width = "full",
					descStyle = "hide",
					get = get,
					set = set,
					arg = "display.showEquipBagSlots",
				},
				sourceexpansion = {
					order = 10,
					type = "toggle",
					name = L.DisplaySourceExpansion,
					width = "full",
					descStyle = "hide",
					get = get,
					set = set,
					arg = "display.enableSourceExpansion",
					hidden = function() return not BSYC.IsRetail end,
				},
				itemtypes = {
					order = 11,
					type = "toggle",
					name = L.DisplayItemTypes,
					width = "full",
					descStyle = "hide",
					get = get,
					set = set,
					arg = "display.enableItemTypes",
				},
				guildbanktabs = {
					order = 12,
					type = "toggle",
					name = L.DisplayGuildBankTabs,
					width = "full",
					descStyle = "hide",
					get = get,
					set = set,
					arg = "display.showGuildTabs",
					disabled = function() return not BSYC.tracking.guild end,
					hidden = function() return not CanGuildBankRepair end,
				},
				warbandbanktabs = {
					order = 13,
					type = "toggle",
					name = L.DisplayWarbandBankTabs,
					width = "full",
					descStyle = "hide",
					get = get,
					set = set,
					arg = "display.showWarbandTabs",
					disabled = function() return not BSYC.tracking.warband end,
					hidden = function() return not BSYC.isWarbandActive end,
				},
			}
		},
```


But if you still want the equippedbags to be at the bottom, the correct numbering would be this.

```
				sourceexpansion = {
					order = 9,
					type = "toggle",
					name = L.DisplaySourceExpansion,
					width = "full",
					descStyle = "hide",
					get = get,
					set = set,
					arg = "display.enableSourceExpansion",
					hidden = function() return not BSYC.IsRetail end,
				},
				itemtypes = {
					order = 10,
					type = "toggle",
					name = L.DisplayItemTypes,
					width = "full",
					descStyle = "hide",
					get = get,
					set = set,
					arg = "display.enableItemTypes",
				},
				guildbanktabs = {
					order = 11,
					type = "toggle",
					name = L.DisplayGuildBankTabs,
					width = "full",
					descStyle = "hide",
					get = get,
					set = set,
					arg = "display.showGuildTabs",
					disabled = function() return not BSYC.tracking.guild end,
					hidden = function() return not CanGuildBankRepair end,
				},
				warbandbanktabs = {
					order = 12,
					type = "toggle",
					name = L.DisplayWarbandBankTabs,
					width = "full",
					descStyle = "hide",
					get = get,
					set = set,
					arg = "display.showWarbandTabs",
					disabled = function() return not BSYC.tracking.warband end,
					hidden = function() return not BSYC.isWarbandActive end,
				},
				equipbagslots = {
					order = 13,
					type = "toggle",
					name = L.DisplayEquipBagSlots,
					width = "full",
					descStyle = "hide",
					get = get,
					set = set,
					arg = "display.showEquipBagSlots",
				},
			}
		},
```

**Comment by nanjuekaien1** [comment]
是不是1
Is the sorting now not a good look.

**Comment by Xruptor** [comment]
Okay I'll fix it. :)

**Comment by nanjuekaien1** [comment]
The 11.0.2 updates arrive to World of Warcraft on August 13!
https://us.forums.blizzard.com/en/wow/t/1102-updates/1914596

**Comment by Xruptor** [comment]
Thanks for the heads up! 💚

**Pull request merged**
