### PR TITLE
Add config option to allow search text box to be auto-focused

### PR DESCRIPTION
**Pull request by mcavanagh**

### CODE REVIEW

**Comment by Xruptor** [comment]
At a casual glance it looks right, but I'll need to do a pull and review it locally.  😄 Looks like just added an option to give the Search bar focus.  I'll take a look at it later this afternoon.

**Comment by Xruptor** [comment]
Okay so the new option shouldn't be a separate group in it's own separate tab.  If anything it should go under the "main" group.  Perhaps above the minimap option.

options.args.main

```

		enableminimap = {
			order = 4,
			type = "toggle",
			name = L.DisplayMinimap,
			width = "full",
			descStyle = "hide",
			get = get,
			set = set,
			arg = "minimap.enableMinimap",
		},
```

You'll have to readjust the order number in each of the fields for options.args.main.  So just add this and reorder.  options.args.display shouldn't needed to be

		focussearcheditbox = {
			order = 4,
			type = "toggle",
			name = L.FocusSearchEditBox,
			width = "full",
			descStyle = "hide",
			get = get,
			set = set,
			arg = "main.focusSearchEditBox",
		},


None of the other "order" numbers in any of the other setting groups should have been touched.  Since that affects the order in which they are displayed within their own groups.  😄   So I would undo any changes to Faq, color, and what not that you did in terms of the numbering.  The only order numbering change should be in the "main" one.  Since we are only adding one new option.

You also don't need to register a new options table for Search at the bottom.  Since we will be using an existing one for "main".

Thanks for your contribution!  Honestly I really do appreciate when folks do pull requests!  It helps me so much keep things going with the addon!

**Comment by mcavanagh** [comment]
Yeah, I wasn't sure it belonged in 'main', which is why I added the new category, but happy to move it.  There's also the issue of localisation strings, but I guess they're not fully complete in every language anyway, so it's not a dealbreaker?

**Comment by Xruptor** [comment]
> Yeah, I wasn't sure it belonged in 'main', which is why I added the new category, but happy to move it. There's also the issue of localisation strings, but I guess they're not fully complete in every language anyway, so it's not a dealbreaker?

Yep it's not fully translated in every language.  As long as there is an English root localization for it, it will work fine.

**Comment by mcavanagh** [comment]
Pushed the changes discussed.  Out of interest, does the 'order' number in config have to be sequential, or could you give yourself wiggle room by using `100`, `200`, etc so you could insert values between them without re-numbering everything?

**Comment by Xruptor** [comment]
> Pushed the changes discussed. Out of interest, does the 'order' number in config have to be sequential, or could you give yourself wiggle room by using `100`, `200`, etc so you could insert values between them without re-numbering everything?

It should be sequential based.  So it should technically work in order even if you use bigger values.  I don't add options often so I just renumber them.  Your idea is actually a really good one and I may do that next time I do add an option.  😄

**Pull request merged**
