### PR TITLE
Update zhCN.lua

### PR DESCRIPTION
**Pull request by nanjuekaien1**

### CODE REVIEW

**Comment by Xruptor** [comment]
WOW! That was quick!  I wasn't expecting it so fast.  Thanks!

**Comment by nanjuekaien1** [comment]
Discuss, next time you need to localize, please add it to zhCN in advance. This way I save a little work. 
Thanks!
^_^

**Comment by Xruptor** [comment]
Hehe yeah but then that adds a little work for me as I would have to add it for each localization as well.  Well that and remember to put it also in the zhCN.  XD  Normally the BagSync changelogs can always view the history for enUS.lua which will tell you all the additions I've done to it.

This is for the commit history for that file
https://github.com/Xruptor/BagSync/commits/master/locale/enUS.lua

This is the raw data for that file.
https://github.com/Xruptor/BagSync/blob/master/locale/enUS.lua

Example, if you click on the first commit history in enUS.lua it takes you to this.
https://github.com/Xruptor/BagSync/commit/5a8621e2458e76777f14fc8a41cece9d56ec1f36

Clicking on enUS.lua on the left will take you right to the change:
https://github.com/Xruptor/BagSync/commit/5a8621e2458e76777f14fc8a41cece9d56ec1f36#diff-dd5e27b6d15cfaa575e614e7c75cba66315a81720b060d730970ddbd459674ec

Hope that helps!!!

**Comment by nanjuekaien1** [comment]
That's how I added it. I just want to be lazy.
^_^

**Pull request merged**
