### PR TITLE
Workaround for missing counts in the profession window

### PR DESCRIPTION
**Pull request by Ignifazius**

### CODE REVIEW

**Comment by Xruptor** [comment]
Any reason this was closed?  I was going to do a pull and merge.  Looks like you corrected some of the issues affecting BagSync at the moment.

**Comment by Ignifazius** [comment]
for some unknown reasons the "TradeSkillFrame" is just "nil" on some of my chars, i'm investigating this issue at the moment

**Comment by Xruptor** [comment]
Ah that would make sense.  When you have everything ready just give the word and I'll push it live.  Thanks for contributing to the code.  Things have been a bit hectic for me recently.

**Comment by Ignifazius** [comment]
Alright, i found the problem: the TradeSkillFrame is "nil" if you haven't opened the profession window before.

**Comment by Xruptor** [comment]
Ah cool.  I believe a poster mentioned something about the ToShortLink() method not working properly and they provided a fix on wowinterface.com (http://www.wowinterface.com/downloads/info15351-BagSync.html#comments).  Another poster mentioned it was actually TradeSkillFrame and posted a fix.  Is this related to the same issue with ToShortLink()?  I can't check for myself but it appears to be related.

**Comment by Ignifazius** [comment]
Yep, that is the same bug... and most of the code i wrote looks very similiar.

**Comment by Xruptor** [comment]
Alright.  When I get a chance back home, i'll go ahead and add a new version number and push it to WOWInterface and CurseForge.

**Comment by Xruptor** [comment]
Pushed the changes live to both Curse and WOWInterface.  Sorry for the delay went on vacation for Labor Day weekened!  LOL.

**Pull request merged**
